# Generated by Django 4.2.2 on 2023-07-24 15:46

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Dados',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(default='nome', max_length=50)),
                ('e_mail', models.CharField(default='mail', max_length=70)),
                ('senha', models.CharField(default='senha', max_length=50)),
                ('codigo', models.CharField(default='nulo', max_length=5)),
            ],
        ),
    ]
