# Generated by Django 4.2.2 on 2023-07-24 21:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('senhas', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='dados',
            name='ativado',
            field=models.BooleanField(default=False),
        ),
    ]
