# Generated by Django 4.2.2 on 2023-07-26 11:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('senhas', '0002_dados_ativado'),
    ]

    operations = [
        migrations.AddField(
            model_name='dados',
            name='logado',
            field=models.BooleanField(default=False),
        ),
    ]
